update GF_Pupils SET STRETCHING_RATING = ROUND(TWINE+FOLD+BUTTERFLY+SHOULDERS, 2)/4;
update GF_Pupils SET STRETCHING_RATING = ROUND(STRETCHING_RATING,2);
update GF_Pupils SET OFP_RATING = ROUND(ANGLE+BRIDGE+FINGER+HANDSTAND+HORIZONT+PUSHUPS, 2)/6;
update GF_Pupils SET OFP_RATING = ROUND(OFP_RATING, 2);
update GF_Pupils SET POWERMOVE_RATING = ROUND(BACKSPIN*0.2+WINDMILL*0.4+TURTLE*0.4+CRICKET*0.6+HEADSPIN*0.4+SWIPES*0.6+NINETY_NINE+FLARE*0.8+AIRFLARE+ELBOWAIRFLARE+MUNCHMILL*0.7+HALO*0.8+JACKHAMMER*0.8+WEB*0.5+WOLF*0.8+UFO, 2)/11;
update GF_Pupils SET POWERMOVE_RATING = ROUND(POWERMOVE_RATING, 2);
update GF_Pupils SET FREZZE_RATING = ROUND(BABY_FREZZE*0.5+TURTLE_FREZZE*0.75+SHOULDER_FREZZE*0.5+HEAD_FREZZE*0.5+HEAD_HOLLOWBACK_FREZZE*0.75+HOLLOWBACK_FREZZE+ELBOW_FREZZE+CHAIR_FREZZE+ONE_HAND_FREZZE+INVERT_FREZZE, 2)/8;
update GF_Pupils SET FREZZE_RATING = ROUND(FREZZE_RATING, 2);
update GF_Pupils SET RATING = ROUND(FREZZE_RATING + POWERMOVE_RATING + OFP_RATING * 0.6 + STRETCHING_RATING * 0.4,2) / 3;
update GF_Pupils SET RATING = ROUND(RATING, 2); 
select *, ROW_NUMBER() OVER(ORDER BY RATING DESC) AS CURRENT_POSITION from GF_Pupils ORDER BY ID;
/* при этом сначала поменять данные из столбца NEW_POSITION в столбец CURRENT_POSITION
    затем скопировать полученые данные в столбец NEW_POSITION */


